eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
spring:
  application:
      name: cloud-provider
  cloud:
    config:
      discovery:
        service-id: cloud-provider
      profile: dev

